"resource/neo_ui/Neo_LoadoutMenu_Dev.res"
{
	"loadout_dev"
	{
		"ControlName"		"CNeoLoadoutMenu_Dev"
		"fieldName"		"loadout_dev"
		"xpos"		"415"
		"ypos"		"159"
		"wide"		"850"
		"tall"		"450"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"0"
		"title"		"#Frame_Untitled"
	}
	"Weapon_ImagePanel"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Weapon_ImagePanel"
		"xpos"		"220"
		"ypos"		"25"
		"wide"		"620"
		"tall"		"385"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"image"		"loadout/none"
		"scaleImage"		"0"
	}	
	"frame_topGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_topGrip"
		"xpos"		"8"
		"ypos"		"0"
		"wide"		"834"
		"tall"		"5"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_bottomGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_bottomGrip"
		"xpos"		"8"
		"ypos"		"445"
		"wide"		"824"
		"tall"		"5"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_leftGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_leftGrip"
		"xpos"		"0"
		"ypos"		"8"
		"wide"		"5"
		"tall"		"434"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_rightGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_rightGrip"
		"xpos"		"845"
		"ypos"		"8"
		"wide"		"5"
		"tall"		"424"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_tlGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_tlGrip"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"8"
		"tall"		"8"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_trGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_trGrip"
		"xpos"		"842"
		"ypos"		"0"
		"wide"		"8"
		"tall"		"8"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_blGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_blGrip"
		"xpos"		"0"
		"ypos"		"442"
		"wide"		"8"
		"tall"		"8"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_brGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_brGrip"
		"xpos"		"832"
		"ypos"		"432"
		"wide"		"18"
		"tall"		"18"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_caption"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_caption"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"840"
		"tall"		"23"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_minimize"
	{
		"ControlName"		"Button"
		"fieldName"		"frame_minimize"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"18"
		"tall"		"18"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"0"
		"textAlignment"		"north-west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"frame_maximize"
	{
		"ControlName"		"Button"
		"fieldName"		"frame_maximize"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"18"
		"tall"		"18"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"1"
		"textAlignment"		"north-west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"frame_mintosystray"
	{
		"ControlName"		"Button"
		"fieldName"		"frame_mintosystray"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"18"
		"tall"		"18"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"o"
		"textAlignment"		"north-west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"MinimizeToSysTray"
		"Default"		"0"
	}
	"frame_close"
	{
		"ControlName"		"Button"
		"fieldName"		"frame_close"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"18"
		"tall"		"18"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"r"
		"textAlignment"		"north-west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"frame_menu"
	{
		"ControlName"		"FrameSystemButton"
		"fieldName"		"frame_menu"
		"xpos"		"7"
		"ypos"		"8"
		"wide"		"18"
		"tall"		"18"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"TitleLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TitleLabel"
		"xpos"		"250"
		"ypos"		"0"
		"wide"		"200"
		"tall"		"16"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"LOADOUT MENU"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Scout_Button"
	{
		"ControlName"		"Button"
		"fieldName"		"Scout_Button"
		"xpos"		"616"
		"ypos"		"291"
		"wide"		"128"
		"tall"		"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"Misc1"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"Command"		"setclass 1"
		"Default"		"0"
	}
	"Misc2"
	{
		"ControlName"		"Button"
		"fieldName"		"Misc2"
		"xpos"		"615"
		"ypos"		"322"
		"wide"		"128"
		"tall"		"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"Misc2"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"setclass 2"
		"Default"		"0"
	}
	"Done_Button"
	{
		"ControlName"		"Button"
		"fieldName"		"Done_Button"
		"xpos"		"776"
		"ypos"		"418"
		"wide"		"64"
		"tall"		"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"GO!"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"playerready"
		"Default"		"0"
	}
	"Button1"
	{
		"ControlName"		"Button"
		"fieldName"		"Button1"
		"xpos"		"10"
		"ypos"		"25"
		"wide"		"200"
		"tall"		"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"MPN45"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"Command"		"loadout 0"
		"Default"		"0"
	}
	"Button2"
	{
		"ControlName"		"Button"
		"fieldName"		"Button2"
		"xpos"		"10"
		"ypos"		"55"
		"wide"		"200"
		"tall"		"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"SRM"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"Command"		"loadout 1"
		"Default"		"0"
	}
	"Button3"
	{
		"ControlName"		"Button"
		"fieldName"		"Button3"
		"xpos"		"10"
		"ypos"		"85"
		"wide"		"200"
		"tall"		"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"SRM (silenced)"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"Command"		"loadout 2"
		"Default"		"0"
	}
	"Button4"
	{
		"ControlName"		"Button"
		"fieldName"		"Button4"
		"xpos"		"10"
		"ypos"		"115"
		"wide"		"200"
		"tall"		"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Jitte"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"Command"		"loadout 3"
		"Default"		"0"
	}
	"Button5"
	{
		"ControlName"		"Button"
		"fieldName"		"Button5"
		"xpos"		"10"
		"ypos"		"145"
		"wide"		"200"
		"tall"		"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Jitte (with scope)"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"Command"		"loadout 4"
		"Default"		"0"
	}
	"Button6"
	{
		"ControlName"		"Button"
		"fieldName"		"Button6"
		"xpos"		"10"
		"ypos"		"175"
		"wide"		"200"
		"tall"		"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"ZR68-C (compact)"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"Command"		"loadout 5"
		"Default"		"0"
	}
	"Button7"
	{
		"ControlName"		"Button"
		"fieldName"		"Button7"
		"xpos"		"10"
		"ypos"		"205"
		"wide"		"200"
		"tall"		"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"ZR68-S (silenced)"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"Command"		"loadout 6"
		"Default"		"0"
	}
	"Button8"
	{
		"ControlName"		"Button"
		"fieldName"		"Button8"
		"xpos"		"10"
		"ypos"		"235"
		"wide"		"200"
		"tall"		"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"ZR68-L (accurized)"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"Command"		"loadout 7"
		"Default"		"0"
	}
	"Button9"
	{
		"ControlName"		"Button"
		"fieldName"		"Button9"
		"xpos"		"10"
		"ypos"		"265"
		"wide"		"200"
		"tall"		"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"MX"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"Command"		"loadout 8"
		"Default"		"0"
	}
	"Button10"
	{
		"ControlName"		"Button"
		"fieldName"		"Button10"
		"xpos"		"10"
		"ypos"		"295"
		"wide"		"200"
		"tall"		"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"PZ252"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"Command"		"loadout 9"
		"Default"		"0"
	}
	"Button11"
	{
		"ControlName"		"Button"
		"fieldName"		"Button11"
		"xpos"		"10"
		"ypos"		"325"
		"wide"		"200"
		"tall"		"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Murata Supa-7"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"Command"		"loadout 10"
		"Default"		"0"
	}
	"Button12"
	{
		"ControlName"		"Button"
		"fieldName"		"Button12"
		"xpos"		"10"
		"ypos"		"355"
		"wide"		"200"
		"tall"		"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Mosok"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"Command"		"loadout 11"
		"Default"		"0"
	}
	"Button13"
	{
		"ControlName"		"Button"
		"fieldName"		"Button13"
		"xpos"		"10"
		"ypos"		"385"
		"wide"		"200"
		"tall"		"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Mosok (with scope)"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"Command"		"loadout 12"
		"Default"		"1"
	}
	"Button14"
	{
		"ControlName"		"Button"
		"fieldName"		"Button14"
		"xpos"		"10"
		"ypos"		"415"
		"wide"		"200"
		"tall"		"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"		"0"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"Command"		"loadout 13"
		"Default"		"0"
	}
//	"Weapon_ImagePanel"
//	{
//		"ControlName"		"ImagePanel"
//		"fieldName"		"Weapon_ImagePanel"
//		"xpos"		"220"
//		"ypos"		"25"
//		"wide"		"620"
//		"tall"		"385"
//		"autoResize"		"1"
//		"pinCorner"		"0"
//		"visible"		"1"
//		"enabled"		"1"
//		"tabPosition"		"0"
//		"image"		"vgui/loadout/none"
//		"scaleImage"		"0"
//	}	
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"fieldName"		"BuildModeDialog"
		"xpos"		"33"
		"ypos"		"60"
		"wide"		"300"
		"tall"		"420"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
}
