"resource/neo_ui/Neo_LoadoutMenu_Dev.res"
{
	"neo_loadoutmenu"
	{
		"ControlName"		"CNeoLoadoutMenu"
		"fieldName"		"neo_loadoutmenu"
		"xpos" "cs-0.5"
		"ypos" "cs-0.5"
		"wide"		"800"
		"tall"		"646"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"0"
		"title"		"#Frame_Untitled"
		"bgcolor"	"200 200 200 255"
	}
//	"Weapon_ImagePanel"
//	{
//		"ControlName"		"ImagePanel"
//		"fieldName"		"Weapon_ImagePanel"
//		"xpos"		"219"
//		"ypos"		"24"
//		"wide"		"619"
//		"tall"		"384"
//		"autoResize"		"1"
//		"pinCorner"		"0"
//		"RoundedCorners"		"15"
//		"pin_corner_to_sibling"		"0"
//		"pin_to_sibling_corner"		"0"
//		"visible"		"1"
//		"enabled"		"1"
//		"tabPosition"		"0"
//		"image"		"loadout/none"
//		"scaleImage"		"0"
//		"scaleAmount"		"0.000000"
//		"tileImage"		"0"
//		"tileHorizontally"		"0"
//		"tileVertically"		"0"
//	}
	"TitleLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TitleLabel"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"800" // why f not working
		"tall"		"16"
		"autoResize"		"1"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"LOADOUT MENU"
		"textAlignment"		"north"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"bgcolor"	"51 51 51 255"
	}
//	"Done_Button"
//	{
//		"ControlName"		"Button"
//		"fieldName"		"Done_Button"
//		"xpos"		"776"
//		"ypos"		"417"
//		"wide"		"64"
//		"tall"		"24"
//		"autoResize"		"1"
//		"pinCorner"		"0"
//		"RoundedCorners"		"15"
//		"pin_corner_to_sibling"		"0"
//		"pin_to_sibling_corner"		"0"
//		"visible"		"1"
//		"enabled"		"1"
//		"tabPosition"		"0"
//		"labelText"		"GO!"
//		"textAlignment"		"center"
//		"dulltext"		"0"
//		"brighttext"		"0"
//		"wrap"		"0"
//		"centerwrap"		"0"
//		"textinsetx"		"6"
//		"textinsety"		"0"
//		"auto_wide_tocontents"		"0"
//		"use_proportional_insets"		"0"
//		"command"		"playerready"
//		"Default"		"0"
//	}
	"Button1Image"
	{
		"ControlName"		"ImagePanel"
		"xpos"		"8"
		"ypos"		"64"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_mpn"
	}
	"Button1"
	{
		"ControlName"		"Button"
		"fieldName"		"Button1"
		"xpos"		"8"
		"ypos"		"64"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"MPN45"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"loadout 0"
		"Default"		"0"
	}
	"Button2Image"
	{
		"ControlName"		"ImagePanel"
		"xpos"		"272"
		"ypos"		"64"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_srm"
	}
	"Button2"
	{
		"ControlName"		"Button"
		"fieldName"		"Button2"
		"xpos"		"272"
		"ypos"		"64"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"SRM"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"loadout 1"
		"Default"		"0"
	}
	"Button3Image"
	{
		"ControlName"		"ImagePanel"
		"xpos"		"536"
		"ypos"		"64"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_srms"
	}
	"Button3"
	{
		"ControlName"		"Button"
		"fieldName"		"Button3"
		"xpos"		"536"
		"ypos"		"64"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"SRM (silenced)"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"loadout 2"
		"Default"		"0"
	}
	"Button4Image"
	{
		"ControlName"		"ImagePanel"
		"xpos"		"8"
		"ypos"		"200"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_jitte"
	}
	"Button4"
	{
		"ControlName"		"Button"
		"fieldName"		"Button4"
		"xpos"		"8"
		"ypos"		"200"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Jitte"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"loadout 3"
		"Default"		"0"
	}
	"Button5Image"
	{
		"ControlName"		"ImagePanel"
		"xpos"		"272"
		"ypos"		"200"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_jittes"
	}
	"Button5"
	{
		"ControlName"		"Button"
		"fieldName"		"Button5"
		"xpos"		"272"
		"ypos"		"200"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Jitte (with scope)"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"loadout 4"
		"Default"		"0"
	}
	"Button6Image"
	{
		"ControlName"		"ImagePanel"
		"xpos"		"536"
		"ypos"		"200"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_zr68c"
	}
	"Button6"
	{
		"ControlName"		"Button"
		"fieldName"		"Button6"
		"xpos"		"536"
		"ypos"		"200"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"ZR68-C (compact)"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"loadout 5"
		"Default"		"0"
	}
	"Button7Image"
	{
		"ControlName"		"ImagePanel"
		"xpos"		"8"
		"ypos"		"336"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_zr68s"
	}
	"Button7"
	{
		"ControlName"		"Button"
		"fieldName"		"Button7"
		"xpos"		"8"
		"ypos"		"336"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"ZR68-S (silenced)"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"loadout 6"
		"Default"		"0"
	}
	"Button8Image"
	{
		"ControlName"		"ImagePanel"
		"xpos"		"272"
		"ypos"		"336"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_zr68l"
	}
	"Button8"
	{
		"ControlName"		"Button"
		"fieldName"		"Button8"
		"xpos"		"272"
		"ypos"		"336"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"ZR68-L (accurized)"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"loadout 7"
		"Default"		"0"
	}
	"Button9Image"
	{
		"ControlName"		"ImagePanel"
		"xpos"		"536"
		"ypos"		"336"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_mx"
	}
	"Button9"
	{
		"ControlName"		"Button"
		"fieldName"		"Button9"
		"xpos"		"536"
		"ypos"		"336"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"MX"
		"textAlignment"		"center"
		"dulltext"		"1"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"loadout 8"
		"Default"		"0"
	}
	"Button10Image"
	{
		"ControlName"		"ImagePanel"
		"xpos"		"8"
		"ypos"		"472"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_pz"
	}
	"Button10"
	{
		"ControlName"		"Button"
		"fieldName"		"Button10"
		"xpos"		"8"
		"ypos"		"472"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"PZ252"
		"textAlignment"		"center"
		"dulltext"		"1"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"loadout 9"
		"Default"		"0"
	}
	"Button11Image"
	{
		"ControlName"		"ImagePanel"
		"xpos"		"272"
		"ypos"		"472"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_supa7"
	}
	"Button11"
	{
		"ControlName"		"Button"
		"fieldName"		"Button11"
		"xpos"		"272"
		"ypos"		"472"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Murata Supa-7"
		"textAlignment"		"center"
		"dulltext"		"1"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"loadout 10"
		"Default"		"0"
	}
	"Button12Image"
	{
		"ControlName"		"ImagePanel"
		"xpos"		"536"
		"ypos"		"472"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_mosok"
	}
	"Button12"
	{
		"ControlName"		"Button"
		"fieldName"		"Button12"
		"xpos"		"536"
		"ypos"		"472"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Mosok"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"loadout 11"
		"Default"		"0"
	}
	"Button13Image"
	{
		"ControlName"		"ImagePanel"
		"xpos"		"272"
		"ypos"		"608"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_mosokl"
	}
	"Button13"
	{
		"ControlName"		"Button"
		"fieldName"		"Button13"
		"xpos"		"272"
		"ypos"		"608"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Mosok (with scope)"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"Default"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"loadout 12"
		"Default"		"0"
	}
	"Button14"
	{
		"ControlName"		"Button"
		"fieldName"		"Button14"
		"xpos"		"272"
		"ypos"		"608"
		"wide"		"256"
		"tall"		"24"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"<< CHANGE CLASS"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"1"
		"Font"		"Default"
		"wrap"		"0"
		"Command"		"loadout 13"
		"Default"		"0"
	}
}
