"resource/neo_ui/Neo_LoadoutMenu_Dev.res"
{
	"neo_loadoutmenu"
	{
		"ControlName"			"CNeoLoadoutMenu"
		"fieldName"				"neo_loadoutmenu"
		"xpos" 					"cs-0.5"
		"ypos" 					"cs-0.5"
		"wide"					"800"
		"tall"					"646"
		"autoResize"			"0"
		"pinCorner"				"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"	"0"
		"pin_to_sibling_corner"	"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"settitlebarvisible"	"0"
		"title"					"#Frame_Untitled"
		"BgColor"				"0 0 0 0"
	}
	"ngui_corner"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"ngui_corner"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"16"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"image"		"ngui_corner"
		"scaleImage"		"0"
	}
	"title_bar"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"title_bar"
		"xpos"		"16"
		"ypos"		"0"
		"wide"		"784"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"image"		"ngui_titlebar"
		"fillcolor"		"black"
		"scaleImage"		"1"
	}
	"background"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"background"
		"xpos"		"0"
		"ypos"		"16"
		"wide"		"f"
		"tall"		"630"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"image"		"ngui_body"
		"scaleImage"		"1"
	}
	"TitleLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TitleLabel"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"800"
		"tall"		"16"
		"autoResize"		"1"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"LOADOUT MENU"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"IconPanel1"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"IconPanel1"
		"xpos"		"272"
		"ypos"		"20"
		"wide"		"256"
		"tall"		"32"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"image"		"choose_primary"
		"scaleImage"		"0"
	}	
	"Button1Image"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Button1Image"
		"xpos"		"8"
		"ypos"		"64"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_none"
	}
	"Button1"
	{
		"ControlName"		"Button"
		"fieldName"		"Button1"
		"xpos"		"8"
		"ypos"		"64"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"command"		"loadout 0"
		"Default"		"0"
	}
	"Button2Image"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Button2Image"
		"xpos"		"272"
		"ypos"		"64"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_none"
	}
	"Button2"
	{
		"ControlName"		"Button"
		"fieldName"		"Button2"
		"xpos"		"272"
		"ypos"		"64"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"command"		"loadout 1"
		"Default"		"0"
	}
	"Button3Image"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Button3Image"
		"xpos"		"536"
		"ypos"		"64"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_none"
	}
	"Button3"
	{
		"ControlName"		"Button"
		"fieldName"		"Button3"
		"xpos"		"536"
		"ypos"		"64"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"command"		"loadout 2"
		"Default"		"0"
	}
	"Button4Image"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Button4Image"
		"xpos"		"8"
		"ypos"		"200"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_none"
	}
	"Button4"
	{
		"ControlName"		"Button"
		"fieldName"		"Button4"
		"xpos"		"8"
		"ypos"		"200"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"command"		"loadout 3"
		"Default"		"0"
	}
	"Button5Image"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Button5Image"
		"xpos"		"272"
		"ypos"		"200"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_none"
	}
	"Button5"
	{
		"ControlName"		"Button"
		"fieldName"		"Button5"
		"xpos"		"272"
		"ypos"		"200"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"command"		"loadout 4"
		"Default"		"0"
	}
	"Button6Image"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Button6Image"
		"xpos"		"536"
		"ypos"		"200"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_none"
	}
	"Button6"
	{
		"ControlName"		"Button"
		"fieldName"		"Button6"
		"xpos"		"536"
		"ypos"		"200"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"command"		"loadout 5"
		"Default"		"0"
	}
	"Button7Image"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Button7Image"
		"xpos"		"8"
		"ypos"		"336"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_none"
	}
	"Button7"
	{
		"ControlName"		"Button"
		"fieldName"		"Button7"
		"xpos"		"8"
		"ypos"		"336"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"command"		"loadout 6"
		"Default"		"0"
	}
	"Button8Image"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Button8Image"
		"xpos"		"272"
		"ypos"		"336"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_none"
	}
	"Button8"
	{
		"ControlName"		"Button"
		"fieldName"		"Button8"
		"xpos"		"272"
		"ypos"		"336"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"command"		"loadout 7"
		"Default"		"0"
	}
	"Button9Image"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Button9Image"
		"xpos"		"536"
		"ypos"		"336"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_none"
	}
	"Button9"
	{
		"ControlName"		"Button"
		"fieldName"		"Button9"
		"xpos"		"536"
		"ypos"		"336"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"command"		"loadout 8"
		"Default"		"0"
	}
	"Button10Image"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Button10Image"
		"xpos"		"8"
		"ypos"		"472"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_none"
	}
	"Button10"
	{
		"ControlName"		"Button"
		"fieldName"		"Button10"
		"xpos"		"8"
		"ypos"		"472"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"command"		"loadout 9"
		"Default"		"0"
	}
	"Button11Image"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Button11Image"
		"xpos"		"272"
		"ypos"		"472"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_none"
	}
	"Button11"
	{
		"ControlName"		"Button"
		"fieldName"		"Button11"
		"xpos"		"272"
		"ypos"		"472"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"command"		"loadout 10"
		"Default"		"0"
	}
	"Button12Image"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Button12Image"
		"xpos"		"536"
		"ypos"		"472"
		"wide"		"256"
		"tall"		"128"
		"image"		"loadout/loadout_none"
	}
	"Button12"
	{
		"ControlName"		"Button"
		"fieldName"		"Button12"
		"xpos"		"536"
		"ypos"		"472"
		"wide"		"256"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"command"		"loadout 11"
		"Default"		"0"
	}
	"ReturnButton"
	{
		"ControlName"		"Button"
		"fieldName"		"ReturnButton"
		"xpos"		"8"
		"ypos"		"608"
		"wide"		"256"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"<< CHANGE CLASS"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"1"
		"Font"		"Default"
		"wrap"		"0"
		"Command"		"classmenu"
		"Default"		"0"
	}
}
